name: Auto Merge Owner PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: flake8 and pylint
      run: |
        pip install -r requirements.txt
        flake8 --ignore=E501,E231 *.py tests/*.py
        pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
    
    - name: unit test
      run: python -m unittest --verbose --failfast
  
  merge:
    if: github.actor == 'automate6500' || github.actor == 'octocat' || github.actor == 'evellyncosta'
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v1
    
    - uses: hmarr/auto-approve-action@v2.0.0
      with:
        set-safe-directory: '*'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global --add safe.directory /github/workspace
    
    - uses: managedkaos/merge-pull-request@v2.2.0
      env:
        set-safe-directory: '*'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git config --global --add safe.directory /github/workspace |
          git config --system --add safe.directory '*' 
